# Project information
site_name: YAN & BILL
site_url: https://ballbill.github.io
site_author: YAN & BILL
# Repository
repo_url: https://github.com/BallBill/ballbill.github.io
repo_name: YAN & BILL
# Copyright
copyright: Copyright &copy; 2024 YAN & BILL
# Configuration
theme:
  name: material
  language: zh-TW
  features:
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
  icon:
    logo: material/cat
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BallBill/ballbill.github.io
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7MNyP7yrdD
# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Page tree
nav:
  - YAN & BILL: index.md
  - Game:
    - game/index.md
    - Albion Online:
      - game/albion_online/index.md
      - Melee Weapons: game/albion_online/ao_melee_weapons.md
      - Magic Weapons: game/albion_online/ao_magic_weapons.md
      - Ranged Weapons: game/albion_online/ao_ranged_weapons.md
      - Off Hand: game/albion_online/ao_off_hand.md
      - Cloth Armor: game/albion_online/ao_cloth_armor.md
      - Lether Armor: game/albion_online/ao_leather_armor.md
      - Plate Armor: game/albion_online/ao_plate_armor.md
      - AVA10: game/albion_online/ava10.md
      - AVA20: game/albion_online/ava20.md
      - ZVZ: game/albion_online/zvz.md
      - ZVZ v1: game/albion_online/zvz_v1.md
    - The Elder Scrolls Online: game/the_elder_scrolls_online.md
    - Game Site: game/game.md
  - Computer:
    - computer/index.md
    - 3D Print: computer/3dprint.md
    - Blog: computer/blog.md
    - Markdown: computer/markdown.md
    - Smart Home: computer/smarthome.md
    - Software: computer/software.md
    - VPN: computer/vpn.md
  - Other:
    - other/index.md
    - Manufacturing: other/manufacturing.md